name: Deploy GCP VM Instances

on:
  workflow_dispatch:
    inputs:
      config_name:
          description: 'Select environment config to deploy'
          required: true
          type: choice
          default: 'lightweight-app'
          options:
            - 'pg-school-db'
            - 'web-app-vm'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Run Deployment
        run: |
          chmod +x scripts/deploy-vm.sh
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            CONFIG="config/${{ github.event.inputs.config_name }}.env"
          else
            CONFIG=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '^config/' | head -n 1)
          fi
          
          ./scripts/deploy-vm.sh "$CONFIG"